### ISSUE TITLE
Use Tor hidden service for transport - both for encryption and port forwarding

### ISSUE THREAD

**Issue by ole-tange** [lbryio/lbry-desktop#5681]
I looked at the network traffic. Some traffic is not encrypted. This means that my ISP will be able to know which video I am watching right now. One of the selling points for LBRY is the lack of mass-surveillance and tracking; so I find unencrypted traffic an unfortunate design decision. I think all network traffic should be encrypted - whether it is sensitive data or not. 

Another problem LBRY has is port forwarding. It is hard to get working everywhere.

Both of these problem could be solved if LBRY used Tor as its primary mean of transport.

When you think of Tor you normally think of Tor-browser, and you may have experienced this as quite slow. This is mostly due to lack of bandwidth of the exit node: There is plenty of bandwidth in the internal tor network. In other words: If you can keep the traffic inside the tor network, you will not experience a huge slow down.

Tor makes it possible to set up Hidden Services. With these you can access a port on another computer and only that port. It works OK as port-forwarding: It takes a few minutes to have the Hidden Service announced, but you can access other Hidden Services immediately. And then you can have access between two nodes that would be restricted by an uncooperative NAT-wall.

Any traffic between a Tor-node and a hidden service is encrypted, so you do not need to add extra encryption.

I hope that a later release will include a tor node, and will primarily use tor as network transport.

**Comment by tzarebczan** [comment]
The content itself on the protocol level is already encrypted, so additional layers are not required for a p2p setup. 

There's a separate issue filed for hopepunching to help with ports on the lbry-sdk repository.

**Comment by ole-tange** [comment]
When I search for: "PROSA" in LBRY, I get this in ngrep:
~~~
T 192.168.1.88:44146 -> 51.79.163.68:50001 [AP] #28385
  {"jsonrpc": "2.0", "method": "blockchain.claimtrie.resolve", "id": 5615, "params": ["lbry://PROSA", "lbry://@PROSA"]}.                                                    
~~~

When I click the video "Konservativ modstand imod masseovervågning" I get:
~~~
T 192.168.1.88:44146 -> 51.79.163.68:50001 [AP] #299978
  {"jsonrpc": "2.0", "method": "blockchain.claimtrie.resolve", "id": 5637, "params": ["lbry://@PROSA#c/Konservativ-modstand-imod-masseoverv--gning#b"]}.
~~~
It is pretty clear this is unencrypted and visible to the ISP as well. It would not have been visible if it had been kept in the Tor network.

Often the metadata is as sensitive as the actual content: If I am calling a suicide line at 2 a.m. while my cell phone is on the middle of a bridge, you really do not need to know the content to know what the call is about.

**Comment by tzarebczan** [comment]
sorry, thought you were referring to the data packets themselves. We plan to move those wallet server calls to encrypted calls, there's an issue for this on the sdk side also.

**Comment by lrq3000** [comment]
@tzarebczan Was this issue with unencrypted wallet server calls fixed by any chance?

**Comment by tzarebczan** [comment]
Not yet, there's still an open issue on the SDK which is used for these calls. We have a few other priorities going and then hope to get to it.

**Comment by yangu-hury** [comment]
That is very serious. That is a decentralized platform. It should be completely anonymous. I can't set this to pass through tor net in the app setting. I recommend to add socket options or just an easy to configure there. Make this tech easy to common people is very important.

**Comment by ole-tange** [comment]
I still do not get it: Why not just keep the unencrypted calls, but run them inside the Tor network on .onion-addresses?

It seems to me like a much easier fix with less coding and fewer things that can compromise the anonymity. It adds benefit of Tor's anonymity protection which is well tested, so if your attacker hosts the controversial video, he will still not know that you are downloading it - even if you downloads blocks of the video from his server.

On top of this you make it less suspicious to run tor traffic, which is a benefit to the Tor community.

Can you explain why this is a bad way forward?
